# Generated by Django 4.2.22 on 2025-12-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_user_username_alter_user_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapisecret",
            name="domain",
            field=models.CharField(default="domain.com", max_length=255),
        ),
    ]
