# Generated by Django 4.2.27 on 2026-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_analysis', '0012_datasourceapimodel_field_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='build_in_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='内置标识键'),
        ),
        migrations.AddField(
            model_name='architecture',
            name='is_build_in',
            field=models.BooleanField(default=False, verbose_name='是否内置'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='build_in_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='内置标识键'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='is_build_in',
            field=models.BooleanField(default=False, verbose_name='是否内置'),
        ),
        migrations.AddField(
            model_name='directory',
            name='build_in_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='内置标识键'),
        ),
        migrations.AddField(
            model_name='directory',
            name='is_build_in',
            field=models.BooleanField(default=False, verbose_name='是否内置'),
        ),
        migrations.AddField(
            model_name='topology',
            name='build_in_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='内置标识键'),
        ),
        migrations.AddField(
            model_name='topology',
            name='is_build_in',
            field=models.BooleanField(default=False, verbose_name='是否内置'),
        ),
    ]
