# Generated by Django 4.2.27 on 2026-06-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operation_analysis", "0013_add_builtin_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Screen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("groups", models.JSONField(blank=True, default=list, help_text="组织", null=True)),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="大屏名称")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("other", models.JSONField(blank=True, help_text="大屏其他配置", null=True)),
                ("view_sets", models.JSONField(default=dict, help_text="大屏视图集配置")),
                ("is_build_in", models.BooleanField(default=False, verbose_name="是否内置")),
                ("build_in_key", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="内置标识键")),
                (
                    "directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screen",
                        to="operation_analysis.directory",
                        verbose_name="所属目录",
                    ),
                ),
            ],
            options={
                "verbose_name": "大屏",
                "db_table": "operation_analysis_screen",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("groups", models.JSONField(blank=True, default=list, help_text="组织", null=True)),
                ("name", models.CharField(max_length=128, unique=True, verbose_name="报表名称")),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                ("other", models.JSONField(blank=True, help_text="报表其他配置", null=True)),
                ("view_sets", models.JSONField(default=dict, help_text="报表视图集配置")),
                ("is_build_in", models.BooleanField(default=False, verbose_name="是否内置")),
                ("build_in_key", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="内置标识键")),
                (
                    "directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="operation_analysis.directory",
                        verbose_name="所属目录",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表",
                "db_table": "operation_analysis_report",
            },
        ),
    ]
