# Generated by Django 4.2.27 on 2026-07-29 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_mgmt', '0041_networkwhitelist_domain_build_in'),
        ('operation_analysis', '0018_dashboardsharelink_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('creator', models.CharField(db_index=True, max_length=32, verbose_name='创建者')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('succeeded', '成功'), ('failed', '失败'), ('unknown', '状态未知')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('trigger_type', models.CharField(choices=[('manual_test', '手动测试'), ('scheduled', '计划执行')], default='manual_test', max_length=16, verbose_name='触发方式')),
                ('request_id', models.CharField(blank=True, default='', max_length=64, verbose_name='请求幂等键')),
                ('failure_stage', models.CharField(blank=True, default='', max_length=64, verbose_name='失败阶段')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='投递时间')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to='operation_analysis.dashboard', verbose_name='仪表盘')),
            ],
            options={
                'verbose_name': '仪表盘报告执行',
                'db_table': 'operation_analysis_dashboard_report_execution',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardReportSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('creator', models.CharField(db_index=True, max_length=32, verbose_name='创建者')),
                ('name', models.CharField(max_length=128, verbose_name='订阅名称')),
                ('status', models.CharField(choices=[('active', '启用'), ('paused', '暂停'), ('terminated', '已终止')], db_index=True, default='active', max_length=16, verbose_name='状态')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='接收邮箱')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_subscriptions', to='operation_analysis.dashboard', verbose_name='仪表盘')),
                ('email_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_subscriptions', to='system_mgmt.channel', verbose_name='邮件通道')),
            ],
            options={
                'verbose_name': '仪表盘报告订阅',
                'db_table': 'operation_analysis_dashboard_report_subscription',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardReportRenderToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Render Token SHA-256')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='到期时间')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='消费时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render_token', to='operation_analysis.dashboardreportexecution', verbose_name='报告执行')),
            ],
            options={
                'verbose_name': '仪表盘报告一次性 Render Token',
                'db_table': 'operation_analysis_dashboard_report_render_token',
            },
        ),
        migrations.CreateModel(
            name='DashboardReportRenderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.BigIntegerField(verbose_name='仪表盘 ID')),
                ('dashboard_name', models.CharField(max_length=128, verbose_name='仪表盘名称')),
                ('dashboard_updated_at', models.DateTimeField(verbose_name='仪表盘更新时间')),
                ('view_sets', models.JSONField(default=list, verbose_name='仪表盘布局')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='筛选配置')),
                ('other', models.JSONField(blank=True, null=True, verbose_name='其他配置')),
                ('widget_manifest', models.JSONField(default=list, verbose_name='Widget 清单')),
                ('datasource_snapshots', models.JSONField(default=list, verbose_name='DataSource 运行快照（审计冻结，当前不驱动取数）')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render_snapshot', to='operation_analysis.dashboardreportexecution', verbose_name='报告执行')),
            ],
            options={
                'verbose_name': '仪表盘报告渲染快照',
                'db_table': 'operation_analysis_dashboard_report_render_snapshot',
            },
        ),
        migrations.CreateModel(
            name='DashboardReportPdfArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_reference', models.CharField(max_length=255, verbose_name='临时存储引用')),
                ('filename', models.CharField(max_length=255, verbose_name='附件文件名')),
                ('size_bytes', models.BigIntegerField(verbose_name='文件大小')),
                ('sha256', models.CharField(max_length=64, verbose_name='内容 SHA-256')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='临时文件到期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='生成时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_artifact', to='operation_analysis.dashboardreportexecution', verbose_name='报告执行')),
            ],
            options={
                'verbose_name': '仪表盘报告 PDF 临时产物',
                'db_table': 'operation_analysis_dashboard_report_pdf_artifact',
            },
        ),
        migrations.CreateModel(
            name='DashboardReportExecutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.BigIntegerField(verbose_name='仪表盘 ID')),
                ('creator_id', models.CharField(max_length=32, verbose_name='创建者 ID')),
                ('creator_timezone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='创建者时区')),
                ('subscription_id', models.BigIntegerField(verbose_name='报告订阅 ID')),
                ('subscription_name', models.CharField(default='', max_length=128, verbose_name='订阅名称')),
                ('recipient_email', models.EmailField(default='', max_length=254, verbose_name='接收邮箱')),
                ('trigger_type', models.CharField(default='', max_length=16, verbose_name='触发方式')),
                ('email_channel_id', models.BigIntegerField(blank=True, null=True, verbose_name='邮件通道 ID')),
                ('filter_values', models.JSONField(blank=True, default=dict, verbose_name='筛选值')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='operation_analysis.dashboardreportexecution', verbose_name='报告执行')),
            ],
            options={
                'verbose_name': '仪表盘报告执行输入快照',
                'db_table': 'operation_analysis_dashboard_report_execution_snapshot',
            },
        ),
        migrations.AddField(
            model_name='dashboardreportexecution',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='operation_analysis.dashboardreportsubscription', verbose_name='报告订阅'),
        ),
        migrations.AddConstraint(
            model_name='dashboardreportexecution',
            constraint=models.UniqueConstraint(
                condition=models.Q(('request_id', ''), _negated=True),
                fields=('subscription', 'request_id', 'trigger_type'),
                name='uniq_dashboard_report_execution_request',
            ),
        ),
    ]
