# Generated by Django 4.2.27 on 2026-07-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_analysis', '0020_dashboard_report_execution'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReportExecutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.BigIntegerField(verbose_name='仪表盘 ID')),
                ('creator_id', models.CharField(max_length=32, verbose_name='创建者 ID')),
                ('subscription_id', models.BigIntegerField(verbose_name='报告订阅 ID')),
                ('filter_values', models.JSONField(blank=True, default=dict, verbose_name='筛选值')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='operation_analysis.dashboardreportexecution', verbose_name='报告执行')),
            ],
            options={
                'verbose_name': '仪表盘报告执行输入快照',
                'db_table': 'operation_analysis_dashboard_report_execution_snapshot',
            },
        ),
    ]
