# Generated by Django 4.2.27 on 2026-07-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation_analysis', '0021_dashboardreportexecutionsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReportRenderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.BigIntegerField(verbose_name='仪表盘 ID')),
                ('dashboard_name', models.CharField(max_length=128, verbose_name='仪表盘名称')),
                ('dashboard_updated_at', models.DateTimeField(verbose_name='仪表盘更新时间')),
                ('view_sets', models.JSONField(default=list, verbose_name='仪表盘布局')),
                ('filters', models.JSONField(blank=True, null=True, verbose_name='筛选配置')),
                ('other', models.JSONField(blank=True, null=True, verbose_name='其他配置')),
                ('widget_manifest', models.JSONField(default=list, verbose_name='Widget 清单')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render_snapshot', to='operation_analysis.dashboardreportexecution', verbose_name='报告执行')),
            ],
            options={
                'verbose_name': '仪表盘报告渲染快照',
                'db_table': 'operation_analysis_dashboard_report_render_snapshot',
            },
        ),
    ]
