# Generated by Django 4.2.7 on 2025-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0006_correlationrules_exec_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aggregationrules",
            name="strategy_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="策略特定参数配置。根据strategy_type存储不同配置：阈值策略存threshold_value等，频率策略存event_count_threshold等", null=True
            ),
        ),
        migrations.AddField(
            model_name="aggregationrules",
            name="default_window_config",
            field=models.JSONField(
                blank=True, default=dict,
                help_text="窗口类型配置，包含window_type、window_size、slide_interval、alignment、session_timeout等",
                null=True
            ),
        ),
        migrations.AddField(
            model_name="aggregationrules",
            name="strategy_type",
            field=models.CharField(
                choices=[
                    ("threshold", "阈值告警"),
                    ("mutation", "突变告警"),
                    ("composite", "复合条件"),
                    ("frequency", "频率告警"),
                    ("trend", "趋势告警"),
                    ("anomaly", "异常检测"),
                ],
                default="composite",
                help_text="告警策略类型：threshold(阈值)/mutation(突变)/composite(复合)/frequency(频率)/trend(趋势)/anomaly(异常)",
                max_length=32,
            ),
        ),
    ]
