# Generated by Django 4.2.22 on 2026-05-24 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0012_event_push_source_id_alter_event_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='collaborators',
            field=models.JSONField(blank=True, default=list, help_text='协作者'),
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(help_text='发布者', max_length=64)),
                ('update_type', models.CharField(choices=[('observation', '观察'), ('progress', '进展'), ('conclusion', '结论'), ('next_step', '下一步')], help_text='更新类型', max_length=32)),
                ('content', models.TextField(help_text='更新内容', max_length=1000)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表')),
                ('is_key_info', models.BooleanField(default=False, help_text='是否标记为关键信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('incident', models.ForeignKey(help_text='关联事故', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='alerts.incident')),
                ('parent', models.ForeignKey(blank=True, help_text='回复的父更新', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='alerts.incidentupdate')),
            ],
            options={
                'db_table': 'alerts_incident_update',
                'ordering': ['-created_at'],
            },
        ),
    ]
