# Generated by Django 4.2.7 on 2026-05-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0012_event_push_source_id_alter_event_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertsource",
            name="team_secrets",
            field=models.JSONField(default=dict, help_text="组织密钥映射 {team_id: secret}"),
        ),
        migrations.AddField(
            model_name="event",
            name="team",
            field=models.JSONField(default=list, help_text="归属组织"),
        ),
        migrations.AddField(
            model_name="incident",
            name="team",
            field=models.JSONField(default=list, help_text="管理组织"),
        ),
    ]
