# Generated by Django 4.2.7 on 2026-05-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0013_alertsource_team_secrets_event_team_incident_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="event", name="ingest_key", field=models.CharField(blank=True, db_index=True, help_text="接入幂等键", max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(fields=("source", "push_source_id", "ingest_key"), name="event_source_push_ingest_key_uniq"),
        ),
    ]
