# Generated by Django 4.2.27 on 2026-06-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0016_alert_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmstrategy',
            name='strategy_type',
            field=models.CharField(choices=[('smart_denoise', '智能降噪'), ('missing_detection', '缺失检测'), ('instant', '即时告警')], default='smart_denoise', help_text='策略类型', max_length=32),
        ),
    ]
