# Generated by Django 4.2.27 on 2026-06-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0017_alarmstrategy_add_instant_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEscalationTask',
            fields=[
                ('alert', models.OneToOneField(help_text='关联的告警', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alerts.alert')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活')),
                ('mode', models.CharField(help_text='升级模式 append/replace', max_length=16)),
                ('layers', models.JSONField(default=list, help_text='升级链层级快照')),
                ('current_layer_index', models.IntegerField(default=0, help_text='当前层级索引')),
                ('layer_started_at', models.DateTimeField(help_text='本层开始时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='分派策略', on_delete=django.db.models.deletion.CASCADE, to='alerts.alertassignment')),
            ],
            options={
                'db_table': 'alerts_escalation_task',
                'indexes': [models.Index(fields=['is_active', 'layer_started_at'], name='alerts_esca_is_acti_2571f2_idx')],
            },
        ),
    ]
