# Generated by Django 4.2.27 on 2026-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0018_alertescalationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='规则名称', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('match_rules', models.JSONField(default=list, help_text='作用范围(OR-of-AND)')),
                ('provider_type', models.CharField(default='cmdb', help_text='数据源类型', max_length=32)),
                ('input_binding', models.JSONField(default=dict, help_text='入参绑定 provider_param->event_field')),
                ('provider_config', models.JSONField(default=dict, help_text='Provider 专属配置')),
                ('output_projection', models.JSONField(default=list, help_text='出参投影 [{source, as}]，空=全取')),
                ('on_multiple', models.CharField(choices=[('first', '取首条'), ('merge', '合并'), ('list', '列表')], default='first', help_text='多结果策略', max_length=16)),
                ('namespace', models.CharField(blank=True, default='', help_text='enrichment 命名空间键', max_length=64)),
                ('team', models.JSONField(default=list, help_text='关联组织')),
            ],
            options={
                'verbose_name': '告警丰富规则',
                'verbose_name_plural': '告警丰富规则',
                'db_table': 'alerts_enrichment_rule',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='enrichment',
            field=models.JSONField(default=dict, help_text='丰富数据，按来源命名空间分区'),
        ),
        migrations.AddField(
            model_name='event',
            name='enrichment',
            field=models.JSONField(default=dict, help_text='丰富数据，按来源命名空间分区'),
        ),
    ]
