# Generated by Django 4.2.27 on 2026-06-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0019_enrichmentrule_alert_enrichment_event_enrichment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("team", models.JSONField(default=list, verbose_name="团队")),
                ("match_rules", models.JSONField(default=list, verbose_name="匹配条件(OR-of-AND)")),
                ("trigger_events", models.JSONField(default=list, verbose_name="触发事件")),
                ("scope", models.CharField(default="alert", max_length=16, verbose_name="作用层级")),
                ("action_type", models.CharField(default="job", max_length=32, verbose_name="动作类型")),
                ("action_config", models.JSONField(default=dict, verbose_name="动作配置")),
            ],
            options={"verbose_name": "告警处理规则", "verbose_name_plural": "告警处理规则", "db_table": "alerts_action_rule",},
        ),
        migrations.CreateModel(
            name="ActionExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("trigger_event", models.CharField(max_length=32, verbose_name="触发事件")),
                ("trigger_type", models.CharField(default="auto", max_length=16, verbose_name="触发方式")),
                ("idempotency_key", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="幂等键")),
                ("status", models.CharField(db_index=True, default="pending", max_length=16, verbose_name="状态")),
                ("action_type", models.CharField(default="job", max_length=32, verbose_name="动作类型")),
                ("job_task_id", models.IntegerField(blank=True, null=True, verbose_name="作业执行ID")),
                ("job_detail_url", models.CharField(blank=True, max_length=512, null=True, verbose_name="作业详情链接")),
                ("result", models.JSONField(blank=True, default=dict, verbose_name="结果")),
                ("operator", models.CharField(blank=True, max_length=64, null=True, verbose_name="手动触发人")),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="action_executions", to="alerts.alert", verbose_name="告警"
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="alerts.actionrule",
                        verbose_name="规则",
                    ),
                ),
            ],
            options={"verbose_name": "动作执行记录", "verbose_name_plural": "动作执行记录", "db_table": "alerts_action_execution", "ordering": ["-created_at"],},
        ),
    ]
