# Generated by Django 4.2

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0022_merge_20260717_0921"),
        ("system_mgmt", "0038_imnotificationchannel_imnotificationusermapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentIMGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("provider_key", models.CharField(default="feishu", max_length=32)),
                ("channel_name_snapshot", models.CharField(max_length=100)),
                ("member_id_type", models.CharField(max_length=32)),
                ("group_name", models.CharField(max_length=255)),
                ("external_chat_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("external_owner_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_create", "待创建"),
                            ("creating", "创建中"),
                            ("active", "正常"),
                            ("active_partial", "部分成功"),
                            ("paused", "已暂停"),
                            ("degraded", "配置异常"),
                            ("create_failed", "创建失败"),
                            ("unlinked", "已解绑"),
                        ],
                        db_index=True,
                        default="pending_create",
                        max_length=32,
                    ),
                ),
                ("active_slot", models.PositiveSmallIntegerField(default=1, editable=False, null=True)),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("queued", "已提交"),
                            ("creating_chat", "创建群"),
                            ("adding_members", "邀请成员"),
                            ("sending_summary", "发送摘要"),
                            ("completed", "已完成"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("continuous_sync_enabled", models.BooleanField(default=True)),
                ("resume_after_reopen", models.BooleanField(default=False)),
                (
                    "pause_reason",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "手工暂停"), ("incident_closed", "Incident 已关闭")],
                        default="",
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=50, unique=True)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=128)),
                ("last_error_message", models.CharField(blank=True, default="", max_length=500)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("unlinked_at", models.DateTimeField(blank=True, null=True)),
                ("unlinked_by", models.CharField(blank=True, default="", max_length=32)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incident_im_groups",
                        to="system_mgmt.imnotificationchannel",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="im_groups",
                        to="alerts.incident",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "active_slot"),
                        name="unique_active_incident_im_group",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentIMMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("username", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(choices=[("operator", "负责人"), ("collaborator", "协作人")], max_length=32),
                ),
                ("external_id", models.CharField(blank=True, default="", max_length=255)),
                ("external_id_type", models.CharField(blank=True, default="", max_length=32)),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[("mapped", "已映射"), ("unmapped", "未映射"), ("conflict", "映射冲突")],
                        default="unmapped",
                        max_length=32,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待映射"),
                            ("pending", "待同步"),
                            ("adding", "同步中"),
                            ("joined", "已入群"),
                            ("failed", "同步失败"),
                        ],
                        default="waiting",
                        max_length=32,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, default="", max_length=128)),
                ("last_error_message", models.CharField(blank=True, default="", max_length=500)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="alerts.incidentimgroup",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["group", "sync_status"], name="incident_im_member_sync_idx"),
                    models.Index(fields=["group", "mapping_status"], name="incident_im_member_mapping_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("group", "username"), name="unique_incident_im_member_username"),
                ],
            },
        ),
    ]
