# Generated by Django 4.2.27 on 2026-07-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0022_merge_20260717_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(blank=True, help_text='告警源（FK；2026-07-17 新增，与 Event.source 对齐，支持按 source.id 过滤分派/屏蔽/富化）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertsource'),
        ),
    ]
