# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0022_incident_im_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentimgroup",
            name="last_reconcile_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
