# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0023_incidentimgroup_last_reconcile_attempt_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentimgroup",
            name="created_by",
            field=models.CharField(default="", max_length=150, verbose_name="Creator"),
        ),
        migrations.AlterField(
            model_name="incidentimgroup",
            name="updated_by",
            field=models.CharField(default="", max_length=150, verbose_name="Updater"),
        ),
        migrations.AlterField(
            model_name="incidentimgroup",
            name="unlinked_by",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
