opspilot: OpsPilot 是AI智能平台，基于前沿人工智能技术，融合机器学习与大模型能力，支持多元化场景
monitor: 用于实时监测和管理系统运行状态的平台，提供数据可视化、告警通知、性能分析等功能，帮助快速定位问题，保障业务稳定
cmdb: 用于集中管理企业的所有IT资产和资源的平台，帮助组织有效地追踪资产生命周期、优化资源分配并确保系统安全
node: 用于集中管理各个云区域下的节点，为各个节点安装各类探针，以便进行监控数据、配置信息、日志等信息的采集
system-manager: 涵盖用户和组织角色权限管理，通过精细化权限控制，确保资源访问安全，同时提升操作效率。提供灵活的配置和管理，满足不同业务需求
mlops: AI模型全生命周期管理工具，集成数据集管理、模型任务训练等功能，提升机器学习的灵活性和效率。
alarm: 汇聚企业多源告警事件，智能降噪，挖掘深层故障原因，提升运维响应效率，帮助快速定位问题。
log: 用于集中收集、存储和分析日志数据，帮助用户实现高效的日志监控和故障排查。
playground: 用户可以在这里体验相关能力，包括 AIOps 模型测试、智能体使用等。
ops-analysis: 整合运维数据，通过仪表盘、画布方式多维度分析挖掘潜在风险与优化空间，为决策提供数据支撑，助力提升运维质量与业务连续性。