/* Generated by scripts/generate-ai-pilots.mjs -- DO NOT EDIT BY HAND */
import type { AiPageContextPilot } from './types';

export const GENERATED_PAGE_CONTEXT_PILOTS: AiPageContextPilot[] = [
  {
    test: (pathname) => pathname.includes('/monitor/view/dashboard/'),
    load: () => import('@/app/monitor/(pages)/view/dashboard/dashboard.pilot'),
  },
  {
    test: (pathname) => pathname.includes('/ops-analysis/view/'),
    load: () => import('@/app/ops-analysis/(pages)/view/dashboard.pilot'),
  },
];

