networks:
  prod:

services:
  telegraf:
    image: ${DOCKER_IMAGE_TELEGRAF}
    container_name: telegraf
    environment:
      METRIC_NATS_USERNAME: ${NATS_ADMIN_USERNAME}
      METRIC_NATS_PASSWORD: ${NATS_ADMIN_PASSWORD}
      METRIC_OUTPUT_URL: http://victoria-metrics:8428
      METRIC_NATS_SERVERS: nats://nats:4222
    volumes:
      - ../conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - prod
    restart: always
    depends_on:
      server:
        condition: service_healthy


  fusion-collector:
    image: ${DOCKER_IMAGE_FUSION_COLLECTOR}
    container_name: fusion-collector
    hostname: fusion-collector-default
    environment:
      SERVER_URL: http://server:8000/api/v1/node_mgmt/open_api/node
      SERVER_API_TOKEN: ${SIDECAR_INIT_TOKEN}
      SIDECAR_ZONE: 1
      SIDECAR_GROUP: 1
      SIDECAR_NODEID: ${SIDECAR_NODE_ID}
      SIDECAR_NODENAME: fusion-collector
    volumes:
      - ../conf/certs:/opt/fusion-collectors/certs:ro
    networks:
      - prod
    restart: always
    depends_on:
      server:
        condition: service_healthy

  stargazer:
    image: ${DOCKER_IMAGE_STARGAZER}
    container_name: stargazer
    environment:
      NATS_URLS: nats://${NATS_ADMIN_USERNAME}:${NATS_ADMIN_PASSWORD}@nats:4222
      UV_OFFLINE: True
    networks:
      - prod