apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lobe-chat-{{bot_id}}
  namespace: {{ bot_namespace }}
spec:  
  entryPoints:
    {% if enable_ssl %}
    - websecure
    {% else %}
    - web
    {% endif %}
  routes:
    - match: Host(`{{bot_domain}}`)
      kind: Rule
      services:
        - name: lobe-chat-{{ bot_id }}-service
          port: 3210