# Generated by Django 4.2.15 on 2025-11-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_monitorplugin_collect_type_monitorplugin_collector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorPluginUITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('content', models.JSONField(default=dict, verbose_name='模版内容')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorplugin', verbose_name='监控插件')),
            ],
            options={
                'verbose_name': '监控插件UI模板',
                'verbose_name_plural': '监控插件UI模板',
            },
        ),
        migrations.CreateModel(
            name='MonitorPluginConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('type', models.CharField(max_length=50, verbose_name='模板类型')),
                ('config_type', models.CharField(default='', max_length=50, verbose_name='配置类型')),
                ('file_type', models.CharField(default='', max_length=50, verbose_name='文件类型')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorplugin', verbose_name='监控插件')),
            ],
            options={
                'verbose_name': '监控插件配置模板',
                'verbose_name_plural': '监控插件配置模板',
                'unique_together': {('plugin', 'type', 'config_type', 'file_type')},
            },
        ),
    ]
