# Generated by Django 4.2.15 on 2025-11-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_monitorpluginuitemplate_monitorpluginconfigtemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorEventRawData',
        ),
    ]
