# Generated by Django 4.2.15 on 2025-11-14 08:49

import apps.core.fields.s3_json_field
from django.db import migrations, models
import django.db.models.deletion


def remove_duplicate_snapshots(apps, schema_editor):
    """删除重复的快照记录，每个告警只保留最新的一条"""
    MonitorAlertMetricSnapshot = apps.get_model('monitor', 'MonitorAlertMetricSnapshot')

    # 查找所有告警ID
    alert_ids = MonitorAlertMetricSnapshot.objects.values_list('alert_id', flat=True).distinct()

    for alert_id in alert_ids:
        # 获取该告警的所有快照，按更新时间倒序
        snapshots = MonitorAlertMetricSnapshot.objects.filter(alert_id=alert_id).order_by('-updated_at')

        # 保留最新的一条，删除其他的
        if snapshots.count() > 1:
            keep_id = snapshots.first().id
            MonitorAlertMetricSnapshot.objects.filter(
                alert_id=alert_id
            ).exclude(id=keep_id).delete()


def set_default_snapshots(apps, schema_editor):
    """为已存在的记录设置默认的空列表"""
    MonitorAlertMetricSnapshot = apps.get_model('monitor', 'MonitorAlertMetricSnapshot')
    # 为所有记录设置空字符串（S3JSONField 将空列表序列化为空字符串）
    MonitorAlertMetricSnapshot.objects.filter(snapshots__isnull=True).update(snapshots='')


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_delete_monitoreventrawdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorEventRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', apps.core.fields.s3_json_field.S3JSONField(bucket_name='monitor-event-raw-data', compressed=True, default=dict, max_length=500, upload_to=apps.core.fields.s3_json_field.s3_json_upload_path, verbose_name='原始数据')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='monitoralertmetricsnapshot',
            name='monitor_mon_alert_i_117b30_idx',
        ),
        migrations.RemoveField(
            model_name='monitoralertmetricsnapshot',
            name='event',
        ),
        migrations.RemoveField(
            model_name='monitoralertmetricsnapshot',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='monitoralertmetricsnapshot',
            name='snapshot_time',
        ),
        # 删除重复的快照记录
        migrations.RunPython(remove_duplicate_snapshots, migrations.RunPython.noop),
        # 先添加允许 NULL 的字段
        migrations.AddField(
            model_name='monitoralertmetricsnapshot',
            name='snapshots',
            field=apps.core.fields.s3_json_field.S3JSONField(
                bucket_name='monitor-alert-snapshots',
                compressed=True,
                default=list,
                max_length=500,
                upload_to=apps.core.fields.s3_json_field.s3_json_upload_path,
                verbose_name='快照数据集合',
                null=True,  # 先允许 NULL
                blank=True
            ),
        ),
        # 为已存在的记录设置默认值
        migrations.RunPython(set_default_snapshots, migrations.RunPython.noop),
        # 再将字段改为 NOT NULL
        migrations.AlterField(
            model_name='monitoralertmetricsnapshot',
            name='snapshots',
            field=apps.core.fields.s3_json_field.S3JSONField(
                bucket_name='monitor-alert-snapshots',
                compressed=True,
                default=list,
                max_length=500,
                upload_to=apps.core.fields.s3_json_field.s3_json_upload_path,
                verbose_name='快照数据集合'
            ),
        ),
        # 将 alert 字段改为 OneToOneField（创建唯一索引）
        migrations.AlterField(
            model_name='monitoralertmetricsnapshot',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoralert', verbose_name='关联告警'),
        ),
        migrations.AddIndex(
            model_name='monitoralertmetricsnapshot',
            index=models.Index(fields=['alert', 'policy_id'], name='monitor_mon_alert_i_89d83a_idx'),
        ),
        migrations.AddField(
            model_name='monitoreventrawdata',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitorevent', verbose_name='事件'),
        ),
    ]
