# Generated by Django 4.2.15 on 2025-11-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_monitoreventrawdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoralertmetricsnapshot',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoralert', unique=True, verbose_name='关联告警'),
        ),
    ]
