# Generated by Django 4.2.15 on 2025-11-19 06:01

import apps.core.fields.s3_json_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_alter_monitoralertmetricsnapshot_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoralertmetricsnapshot',
            name='snapshots',
            field=apps.core.fields.s3_json_field.S3JSONField(bucket_name='monitor-alert-raw-data', compressed=True, default=list, max_length=500, upload_to=apps.core.fields.s3_json_field.s3_json_upload_path, verbose_name='快照数据集合'),
        ),
        migrations.AlterField(
            model_name='monitoreventrawdata',
            name='data',
            field=apps.core.fields.s3_json_field.S3JSONField(bucket_name='monitor-alert-raw-data', compressed=True, default=dict, max_length=500, upload_to=apps.core.fields.s3_json_field.s3_json_upload_path, verbose_name='原始数据'),
        ),
    ]
