# Generated by Django 4.2.15 on 2025-11-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_alter_monitoralertmetricsnapshot_snapshots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorevent',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitor.monitoralert', verbose_name='关联告警'),
        ),
        migrations.AddIndex(
            model_name='monitorevent',
            index=models.Index(fields=['alert', 'created_at'], name='monitor_mon_alert_i_c262cc_idx'),
        ),
    ]
