# Generated by Django 4.2.15 on 2025-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_monitorevent_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorplugin',
            name='status_query',
            field=models.TextField(blank=True, verbose_name='状态查询语句(PromQL)'),
        ),
    ]
