# Generated by Django 4.2.15 on 2025-12-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_monitorplugin_status_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorplugin',
            name='is_pre',
            field=models.BooleanField(default=True, verbose_name='是否内置'),
        ),
    ]
