# Generated by Django 4.2.27 on 2026-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0029_remove_monitorcondition_monitor_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
    ]
