# Generated by Django 4.2.27 on 2026-03-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0030_monitorobject_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='监控对象显示名称'),
        ),
    ]
