# Generated by Django 4.2.27 on 2026-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0036_notice_type_id_to_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorobject',
            name='display_fields',
            field=models.JSONField(default=list, verbose_name='视图列表展示列配置'),
        ),
        migrations.AddField(
            model_name='monitorobject',
            name='display_fields_customized',
            field=models.BooleanField(default=False, verbose_name='展示列是否被用户自定义'),
        ),
    ]
