# Generated by Django 4.2.27 on 2026-06-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0037_monitorinstance_flow_fields'),
        ('monitor', '0037_monitorobject_display_fields_and_more'),
    ]

    operations = [
    ]
