# Generated by Django 4.2.22 on 2025-12-01 07:35

import apps.core.fields.s3_json_field
from django.db import migrations, models
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0031_objectdetectiondataset_objectdetectiontraindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriespredicttraindata',
            name='metadata',
            field=apps.core.fields.s3_json_field.S3JSONField(blank=True, bucket_name='munchkin-public', compressed=True, help_text='存储在MinIO中的训练数据元信息文件路径', max_length=500, null=True, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttraindata',
            name='train_data',
            field=models.FileField(blank=True, help_text='存储在MinIO中的CSV训练数据文件', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='训练数据'),
        ),
    ]
