# Generated by Django 4.2.22 on 2025-12-02 07:17

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0032_alter_timeseriespredicttraindata_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesPredictDatasetRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='数据集发布版本的名称', max_length=100, verbose_name='发布版本名称')),
                ('description', models.TextField(blank=True, help_text='发布版本的详细描述', null=True, verbose_name='版本描述')),
                ('version', models.CharField(help_text='数据集版本号，如 v1.0.0', max_length=50, verbose_name='版本号')),
                ('dataset_file', models.FileField(help_text='存储在MinIO中的数据集ZIP压缩包', storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='数据集压缩包')),
                ('file_size', models.BigIntegerField(default=0, help_text='压缩包文件大小（字节）', verbose_name='文件大小')),
                ('status', models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '发布失败')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态')),
                ('dataset', models.ForeignKey(help_text='关联的数据集', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='mlops.timeseriespredictdataset', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '时间序列预测数据集发布版本',
                'verbose_name_plural': '时间序列预测数据集发布版本',
                'ordering': ['-created_at'],
                'unique_together': {('dataset', 'version')},
            },
        ),
    ]
