# Generated by Django 4.2.22 on 2025-12-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0033_timeseriespredictdatasetrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriespredictdatasetrelease',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='数据集的统计信息和质量指标，不包含训练配置', verbose_name='数据集元信息'),
        ),
    ]
