# Generated by Django 4.2.22 on 2025-12-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0034_timeseriespredictdatasetrelease_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriespredictdatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
    ]
