# Generated by Django 4.2.22 on 2025-12-16 09:10

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0035_alter_timeseriespredictdatasetrelease_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseriespredicttrainhistory',
            name='test_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainhistory',
            name='train_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainhistory',
            name='val_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainjob',
            name='test_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainjob',
            name='train_data_id',
        ),
        migrations.RemoveField(
            model_name='timeseriespredicttrainjob',
            name='val_data_id',
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainhistory',
            name='config_url',
            field=models.FileField(blank=True, help_text='MinIO 中的 JSON 文件备份', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='配置文件备份'),
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainhistory',
            name='dataset_version',
            field=models.ForeignKey(default=1, help_text='关联的时间序列预测数据集版本', on_delete=django.db.models.deletion.CASCADE, related_name='train_histories', to='mlops.timeseriespredictdatasetrelease', verbose_name='数据集版本'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainjob',
            name='config_url',
            field=models.FileField(blank=True, help_text='MinIO 中的 JSON 文件备份', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='配置文件备份'),
        ),
        migrations.AddField(
            model_name='timeseriespredicttrainjob',
            name='dataset_version',
            field=models.ForeignKey(default=1, help_text='关联的时间序列预测数据集版本', on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.timeseriespredictdatasetrelease', verbose_name='数据集版本'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainhistory',
            name='algorithm',
            field=models.CharField(choices=[('Prophet', 'Prophet'), ('GradientBoosting', 'GradientBoosting')], help_text='使用的时间序列预测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainhistory',
            name='hyperopt_config',
            field=models.JSONField(blank=True, default=dict, help_text='存储在数据库中，供API快速返回', verbose_name='训练配置'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainjob',
            name='algorithm',
            field=models.CharField(choices=[('Prophet', 'Prophet'), ('GradientBoosting', 'GradientBoosting')], help_text='使用的时间序列预测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainjob',
            name='hyperopt_config',
            field=models.JSONField(blank=True, default=dict, help_text='存储在数据库中，供API快速返回', verbose_name='训练配置'),
        ),
    ]
