# Generated by Django 4.2.22 on 2025-12-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0036_remove_timeseriespredicttrainhistory_test_data_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriespredictserving',
            name='container_info',
            field=models.JSONField(blank=True, default=dict, help_text='webhookd 返回的容器实时状态，格式：{status, id, state, port, detail, ...}', verbose_name='容器状态信息'),
        ),
        migrations.AlterField(
            model_name='timeseriespredictserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='用户意图：是否希望服务运行', max_length=20, verbose_name='服务状态'),
        ),
    ]
