# Generated by Django 4.2.22 on 2025-12-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0037_timeseriespredictserving_container_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriespredictserving',
            name='port',
            field=models.IntegerField(blank=True, help_text='用户指定端口，为空则由 docker 自动分配。实际端口以 container_info.port 为准', null=True, verbose_name='服务端口'),
        ),
    ]
