# Generated by Django 4.2.22 on 2026-01-16 03:07

from django.db import migrations, models
import django.db.models.deletion
import django_minio_backend.models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0038_imageclassificationdatasetrelease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDetectionDatasetRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='数据集发布版本的名称', max_length=100, verbose_name='发布版本名称')),
                ('description', models.TextField(blank=True, help_text='发布版本的详细描述', null=True, verbose_name='版本描述')),
                ('version', models.CharField(help_text='数据集版本号，如 v1.0.0', max_length=50, verbose_name='版本号')),
                ('dataset_file', models.FileField(help_text='存储在 MinIO 中的完整 YOLO 数据集 ZIP 压缩包，包含 train/val/test 目录和 data.yaml', storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='数据集压缩包')),
                ('file_size', models.BigIntegerField(default=0, help_text='压缩包文件大小（字节）', verbose_name='文件大小')),
                ('status', models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='\n        完整数据集的统计信息，格式：\n        {\n            "total_images": 1000,\n            "classes": ["person", "car", "dog"],\n            "num_classes": 3,\n            "format": "YOLO",\n            "splits": {\n                "train": {"total": 800, "classes": {"person": 400, "car": 250, "dog": 150}},\n                "val": {"total": 100, "classes": {"person": 50, "car": 30, "dog": 20}},\n                "test": {"total": 100, "classes": {"person": 50, "car": 30, "dog": 20}}\n            }\n        }\n        ', verbose_name='数据集元信息')),
                ('dataset', models.ForeignKey(help_text='关联的数据集', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='mlops.objectdetectiondataset', verbose_name='数据集')),
            ],
            options={
                'verbose_name': '目标检测数据集发布版本',
                'verbose_name_plural': '目标检测数据集发布版本',
                'ordering': ['-created_at'],
                'unique_together': {('dataset', 'version')},
            },
        ),
        migrations.AlterModelOptions(
            name='objectdetectiontraindata',
            options={'verbose_name': '目标检测训练数据', 'verbose_name_plural': '目标检测训练数据'},
        ),
        migrations.RemoveField(
            model_name='objectdetectiontraindata',
            name='meta_data',
        ),
        migrations.AddField(
            model_name='objectdetectiontraindata',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='YOLO 数据集元信息，格式：\n        {\n            "format": "YOLO",\n            "classes": ["person", "car", "dog"],\n            "num_classes": 3,\n            "num_images": 100,\n            "labels": {\n                "img001.jpg": [\n                    {\n                        "class_id": 0,\n                        "class_name": "person",\n                        "x_center": 0.512345,\n                        "y_center": 0.623456,\n                        "width": 0.234567,\n                        "height": 0.345678\n                    }\n                ],\n                "img002.jpg": []\n            },\n            "statistics": {\n                "total_annotations": 250,\n                "images_with_annotations": 95,\n                "images_without_annotations": 5,\n                "class_distribution": {"person": 120, "car": 80, "dog": 50}\n            }\n        }\n        注意：\n        - labels 字段是必需的，包含每张图片的详细标注信息\n        - 坐标值（x_center, y_center, width, height）必须是归一化的（0-1范围）\n        - class_id 从 0 开始，与 classes 数组索引对应\n        - class_name 是冗余字段但建议包含，方便阅读和调试\n        ', verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='objectdetectiontraindata',
            name='train_data',
            field=models.FileField(blank=True, help_text='存储在 MinIO 中的 YOLO 格式 ZIP 压缩包（images/ + labels/ + classes.txt）', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='训练数据'),
        ),
        migrations.CreateModel(
            name='ObjectDetectionTrainJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('status', models.CharField(choices=[('pending', '待训练'), ('running', '训练中'), ('completed', '已完成'), ('failed', '训练失败')], default='pending', help_text='训练任务的当前状态', max_length=20, verbose_name='任务状态')),
                ('algorithm', models.CharField(choices=[('YOLODetection', 'YOLODetection')], default='YOLODetection', help_text='使用的 YOLOv11 目标检测算法模型', max_length=50, verbose_name='算法模型')),
                ('hyperopt_config', models.JSONField(blank=True, default=dict, help_text='\n        前端传递的超参数配置，格式：\n        {\n            "hyperparams": {\n                "epochs": 100,\n                "batch_size": 16,\n                "img_size": 640,\n                "learning_rate": 0.01,\n                "optimizer": "Adam",\n                "conf_threshold": 0.25,\n                "iou_threshold": 0.45,\n                "patience": 10,\n                "workers": 8,\n                "device": "0",\n                "augmentation": {...}\n            }\n        }\n        ', verbose_name='训练配置')),
                ('config_url', models.FileField(blank=True, help_text='MinIO 中的完整训练配置 JSON 文件备份', null=True, storage=django_minio_backend.models.MinioBackend(bucket_name='munchkin-public'), upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='配置文件备份')),
                ('max_evals', models.IntegerField(default=50, help_text='超参数优化的最大评估次数', verbose_name='最大评估次数')),
                ('dataset_version', models.ForeignKey(blank=True, help_text='关联的目标检测数据集版本', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_jobs', to='mlops.objectdetectiondatasetrelease', verbose_name='数据集版本')),
            ],
            options={
                'verbose_name': '目标检测训练任务',
                'verbose_name_plural': '目标检测训练任务',
            },
        ),
        migrations.CreateModel(
            name='ObjectDetectionServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('name', models.CharField(help_text='服务的名称', max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(blank=True, help_text='服务的详细描述', null=True, verbose_name='服务描述')),
                ('model_version', models.CharField(default='latest', help_text='模型版本号，latest 或具体版本（1, 2, 3...）', max_length=50, verbose_name='模型版本')),
                ('port', models.IntegerField(blank=True, help_text='用户指定端口，为空则由 docker 自动分配。实际端口以 container_info.port 为准', null=True, verbose_name='服务端口')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='用户意图：是否希望服务运行', max_length=20, verbose_name='服务状态')),
                ('container_info', models.JSONField(blank=True, default=dict, help_text='webhookd 返回的容器实时状态，格式：{status, id, state, port, detail, ...}', verbose_name='容器状态信息')),
                ('train_job', models.ForeignKey(help_text='关联的目标检测训练任务', on_delete=django.db.models.deletion.CASCADE, related_name='servings', to='mlops.objectdetectiontrainjob', verbose_name='训练任务')),
            ],
            options={
                'verbose_name': '目标检测服务',
                'verbose_name_plural': '目标检测服务',
                'ordering': ['-created_at'],
            },
        ),
    ]
