# Generated by Django 4.2.22 on 2025-12-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0038_timeseriespredictserving_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriespredicttrainhistory',
            name='algorithm',
            field=models.CharField(choices=[('Prophet', 'Prophet'), ('GradientBoosting', 'GradientBoosting'), ('RandomForest', 'RandomForest'), ('Sktime', 'Sktime')], help_text='使用的时间序列预测算法模型', max_length=50, verbose_name='算法模型'),
        ),
        migrations.AlterField(
            model_name='timeseriespredicttrainjob',
            name='algorithm',
            field=models.CharField(choices=[('Prophet', 'Prophet'), ('GradientBoosting', 'GradientBoosting'), ('RandomForest', 'RandomForest'), ('Sktime', 'Sktime')], help_text='使用的时间序列预测算法模型', max_length=50, verbose_name='算法模型'),
        ),
    ]
