# Generated by Django 4.2.27 on 2026-01-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0039_objectdetectiondatasetrelease_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalydetectionserving',
            old_name='anomaly_detection_train_job',
            new_name='train_job',
        ),
        migrations.RenameField(
            model_name='classificationserving',
            old_name='classification_train_job',
            new_name='train_job',
        ),
        migrations.RenameField(
            model_name='logclusteringserving',
            old_name='log_clustering_train_job',
            new_name='train_job',
        ),
        migrations.RenameField(
            model_name='timeseriespredictserving',
            old_name='time_series_predict_train_job',
            new_name='train_job',
        ),
    ]
