# Generated by Django 4.2.27 on 2026-01-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0040_rename_anomaly_detection_train_job_anomalydetectionserving_train_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalydetectiondatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('processing', '发布中'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='classificationdatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('processing', '发布中'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='imageclassificationdatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('processing', '发布中'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='logclusteringdatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('processing', '发布中'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='objectdetectiondatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('processing', '发布中'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
        migrations.AlterField(
            model_name='timeseriespredictdatasetrelease',
            name='status',
            field=models.CharField(choices=[('pending', '待发布'), ('processing', '发布中'), ('published', '已发布'), ('failed', '发布失败'), ('archived', '归档')], default='pending', help_text='数据集发布状态', max_length=20, verbose_name='发布状态'),
        ),
    ]
