# Generated by Django 4.2.22 on 2026-01-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0041_logclusteringdatasetrelease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logclusteringtrainjob',
            name='algorithm',
            field=models.CharField(choices=[('KMeans', 'K-Means'), ('DBSCAN', 'DBSCAN'), ('AgglomerativeClustering', '层次聚类'), ('Drain', 'Drain'), ('LogCluster', 'LogCluster'), ('Spell', 'Spell')], help_text='使用的日志聚类算法模型', max_length=50, verbose_name='算法模型'),
        ),
    ]
