# Generated by Django 4.2.27 on 2026-03-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlops', '0043_algorithmconfig_and_remove_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationserving',
            name='model_version',
            field=models.CharField(default='latest', help_text='模型版本号，如 1, 2, latest 等', max_length=50, verbose_name='模型版本'),
        ),
        migrations.AlterField(
            model_name='anomalydetectionserving',
            name='model_version',
            field=models.CharField(default='latest', help_text='模型版本号，如 1, 2, latest 等', max_length=50, verbose_name='模型版本'),
        ),
        migrations.AlterField(
            model_name='anomalydetectionserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='发布状态(弃用，以容器状态为准)', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='classificationserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='发布状态(弃用，以容器状态为准)', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='imageclassificationserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='发布状态(弃用，以容器状态为准)', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='logclusteringserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='发布状态(弃用，以容器状态为准)', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='objectdetectionserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='发布状态(弃用，以容器状态为准)', max_length=20, verbose_name='服务状态'),
        ),
        migrations.AlterField(
            model_name='timeseriespredictserving',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='发布状态(弃用，以容器状态为准)', max_length=20, verbose_name='服务状态'),
        ),
    ]
