# Generated by Django 4.2.22 on 2025-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0032_skilltools_tools_workflowconversationhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="instance_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name="实例ID"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="instance_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name="Instance ID"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="instance_id",
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, verbose_name="实例ID"),
        ),
    ]
