# Generated by Django 4.2.22 on 2025-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0033_bot_instance_id_knowledgedocument_instance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowconversationhistory",
            name="node_id",
            field=models.CharField(db_index=True, default="", help_text="WorkFlow节点入口ID", max_length=100, verbose_name="节点ID"),
        ),
        migrations.AddIndex(
            model_name="workflowconversationhistory",
            index=models.Index(fields=["node_id", "-conversation_time"], name="bot_mgmt_wo_node_id_601683_idx"),
        ),
    ]
