# Generated by Django 4.2.22 on 2025-12-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0035_chatapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowconversationhistory",
            name="session_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
