# Generated by Django 4.2.22 on 2025-12-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opspilot', '0036_workflowconversationhistory_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconversationhistory',
            name='entry_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('restful', 'RESTful'), ('celery', 'Celery'), ('enterprise_wechat', 'Enterprise WeChat'), ('wechat_official', 'WeChat Official Account'), ('dingtalk', 'Ding Talk'), ('embedded_chat', 'Embedded Chat'), ('web_chat', 'Web Chat'), ('mobile', 'Mobile')], db_index=True, default='restful', help_text='对话入口类型：openai/restful/enterprise_wechat/wechat_official/dingtalk，celery定时触发不记录', max_length=50, verbose_name='入口类型'),
        ),
    ]
