# Generated by Django 4.2.22 on 2025-12-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0037_delete_quotarule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpageknowledge",
            name="last_run_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
