# Generated by Django 4.2.22 on 2025-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0038_webpageknowledge_last_run_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="error_message",
            field=models.TextField(blank=True, null=True, verbose_name="error message"),
        ),
        migrations.AddField(
            model_name="bot",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
        migrations.AddField(
            model_name="llmskill",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
    ]
