# Generated by Django 4.2.22 on 2026-01-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0039_knowledgedocument_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
    ]
