# Generated by Django 4.2.22 on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0040_bot_is_builtin"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="is_builtin",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否内置"),
        ),
    ]
