# Generated by Django 4.2.27 on 2026-05-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0049_modelvendor_protocol_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemorySpace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(db_index=True, max_length=100, verbose_name="名称")),
                ("introduction", models.TextField(blank=True, default="", verbose_name="简介")),
                ("team", models.JSONField(default=list)),
                ("scope", models.CharField(choices=[("personal", "个人"), ("team", "团队")], default="team", max_length=20, verbose_name="可见范围")),
                ("write_rule", models.TextField(blank=True, default="", verbose_name="写入规则")),
                ("default_model", models.CharField(blank=True, default="", max_length=100, verbose_name="默认模型")),
            ],
            options={
                "verbose_name": "记忆空间",
                "verbose_name_plural": "记忆空间",
                "db_table": "memory_mgmt_memoryspace",
            },
        ),
        migrations.CreateModel(
            name="Memory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                ("owner_username", models.CharField(db_index=True, max_length=150, verbose_name="创建者用户名")),
                ("owner_domain", models.CharField(db_index=True, max_length=255, verbose_name="创建者域")),
                (
                    "memory_space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memories", to="opspilot.memoryspace", verbose_name="记忆空间"
                    ),
                ),
            ],
            options={
                "verbose_name": "记忆",
                "verbose_name_plural": "记忆",
                "db_table": "memory_mgmt_memory",
                "indexes": [models.Index(fields=["owner_username", "owner_domain"], name="memory_mgmt_owner_u_4c6539_idx")],
            },
        ),
    ]
