# Generated by Django 4.2.27 on 2026-06-03 08:40

import django.db.models.deletion
from django.db import migrations, models

import apps.opspilot.models.bot_mgmt


class Migration(migrations.Migration):
    dependencies = [
        ("opspilot", "0052_memoryspace_storage_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowAttachmentAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("execution_id", models.CharField(db_index=True, max_length=36, verbose_name="执行实例ID")),
                ("flow_id", models.CharField(blank=True, default="", max_length=36, verbose_name="工作流ID")),
                ("source_node_id", models.CharField(blank=True, default="", max_length=100, verbose_name="来源节点ID")),
                ("attachment_id", models.CharField(max_length=100, verbose_name="附件ID")),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                ("mime_type", models.CharField(blank=True, default="", max_length=120, verbose_name="MIME类型")),
                ("created_by", models.CharField(blank=True, default="", max_length=100, verbose_name="创建者")),
                (
                    "download_token",
                    models.CharField(
                        db_index=True,
                        default=apps.opspilot.models.bot_mgmt.generate_workflow_attachment_download_token,
                        max_length=32,
                        unique=True,
                        verbose_name="下载令牌",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "工作流附件",
                "verbose_name_plural": "工作流附件",
                "db_table": "bot_mgmt_workflowattachmentasset",
            },
        ),
        migrations.AddField(
            model_name="workflowattachmentasset",
            name="file_knowledge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="workflow_attachments", to="opspilot.fileknowledge", verbose_name="附件文件"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowattachmentasset",
            index=models.Index(fields=["execution_id", "created_at"], name="bot_mgmt_wo_executi_9a0839_idx"),
        ),
        migrations.AddConstraint(
            model_name="workflowattachmentasset",
            constraint=models.UniqueConstraint(fields=("execution_id", "attachment_id"), name="uniq_workflow_attachment_execution"),
        ),
    ]
