# Generated by Django 4.2.27 on 2026-06-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opspilot', '0054_memorywritecache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='memory',
            new_name='memory_mgmt_organiz_0c67ee_idx',
            old_name='memory_mgmt_organiz_a1b2c3_idx',
        ),
        migrations.AddField(
            model_name='knowledgetask',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='api_token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='API Token'),
        ),
        migrations.AlterField(
            model_name='embedprovider',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embed_models', to='opspilot.modelvendor', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='knowledgegraph',
            name='llm_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opspilot.llmmodel'),
        ),
        migrations.AlterField(
            model_name='knowledgetask',
            name='created_by',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='knowledgetask',
            name='domain',
            field=models.CharField(db_index=True, default='domain.com', max_length=100, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='knowledgetask',
            name='is_qa_task',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is QA Task'),
        ),
        migrations.AlterField(
            model_name='knowledgetask',
            name='knowledge_base_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Knowledge IDs'),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='llm_models', to='opspilot.modelvendor', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='ocrprovider',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocr_models', to='opspilot.modelvendor', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='rerankprovider',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rerank_models', to='opspilot.modelvendor', verbose_name='供应商'),
        ),
    ]
