# Generated by Django 4.2.22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0056_alter_workflowconversationhistory_entry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowtaskresult",
            name="is_test",
            field=models.BooleanField(db_index=True, default=False, verbose_name="是否测试执行"),
        ),
    ]
