# Generated by Django 4.2.27 on 2026-06-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0057_remove_fileknowledge_knowledge_document_and_more"),
        ("opspilot", "0057_workflowtaskresult_is_test"),
    ]

    operations = []
