# Generated by Django 4.2.27 on 2026-06-22 05:59

import django.db.models.deletion
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0059_remove_fileknowledge_knowledge_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("trigger", models.CharField(default="material", max_length=30)),
                ("operator", models.CharField(blank=True, default="", max_length=100)),
                ("inputs", models.JSONField(default=dict)),
                ("stage", models.CharField(default="queued", max_length=30)),
                ("progress", models.FloatField(default=0)),
                ("counts", models.JSONField(default=dict)),
                ("affected_pages", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                ("status", models.CharField(default="running", max_length=20)),
            ],
            options={
                "db_table": "opspilot_wiki_build_record",
            },
        ),
        migrations.CreateModel(
            name="KnowledgePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("page_type", models.CharField(max_length=50)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("tags", models.JSONField(default=list)),
                ("contribution", models.CharField(default="ai", max_length=20)),
                ("update_method", models.CharField(blank=True, default="", max_length=30)),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            options={
                "db_table": "opspilot_wiki_page",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("material_type", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django_minio_backend.models.MinioBackend(bucket_name="munchkin-private"),
                        upload_to=django_minio_backend.models.iso_date_prefix,
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("text_content", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("ai_summary", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "opspilot_wiki_material",
            },
        ),
        migrations.CreateModel(
            name="MaterialVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("content_locator", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="opspilot.material")),
            ],
            options={
                "db_table": "opspilot_wiki_material_version",
            },
        ),
        migrations.CreateModel(
            name="WikiKnowledgeBase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("introduction", models.TextField(blank=True, default="")),
                ("team", models.JSONField(default=list)),
                ("purpose_md", models.TextField(default="", verbose_name="Purpose Markdown")),
                ("schema_md", models.TextField(default="", verbose_name="Schema Markdown")),
                ("generation_language", models.CharField(default="zh", max_length=20)),
                ("generation_rules", models.JSONField(default=dict)),
                ("web_sync_policy", models.JSONField(default=dict)),
                ("risk_rules", models.JSONField(default=dict)),
                ("template_key", models.CharField(default="general", max_length=50)),
                ("status", models.CharField(default="active", max_length=20)),
                (
                    "embed_provider",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="opspilot.embedprovider"),
                ),
                ("llm_model", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="opspilot.llmmodel")),
            ],
            options={
                "db_table": "opspilot_wiki_knowledge_base",
            },
        ),
        migrations.CreateModel(
            name="PageVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("no", models.IntegerField(default=1)),
                ("body", models.TextField(default="")),
                ("meta_snapshot", models.JSONField(default=dict)),
                ("change_type", models.CharField(max_length=30)),
                ("is_current", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, default="", max_length=100)),
                (
                    "build_record",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.buildrecord"
                    ),
                ),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="page_versions", to="opspilot.knowledgepage")),
            ],
            options={
                "db_table": "opspilot_wiki_page_version",
            },
        ),
        migrations.CreateModel(
            name="PageRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("relation_type", models.CharField(max_length=30)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "from_page",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relations_out", to="opspilot.knowledgepage"),
                ),
                ("to_page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relations_in", to="opspilot.knowledgepage")),
                (
                    "via_material",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.material"),
                ),
            ],
            options={
                "db_table": "opspilot_wiki_page_relation",
            },
        ),
        migrations.CreateModel(
            name="PageEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("locator", models.TextField(blank=True, default="")),
                ("material", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidences", to="opspilot.material")),
                (
                    "material_version",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.materialversion"
                    ),
                ),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidences", to="opspilot.knowledgepage")),
            ],
            options={
                "db_table": "opspilot_wiki_page_evidence",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="current_version",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.materialversion"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="knowledge_base",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="materials", to="opspilot.wikiknowledgebase"),
        ),
        migrations.AddField(
            model_name="knowledgepage",
            name="current_version",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.pageversion"),
        ),
        migrations.AddField(
            model_name="knowledgepage",
            name="knowledge_base",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="opspilot.wikiknowledgebase"),
        ),
        migrations.CreateModel(
            name="CheckItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("check_type", models.CharField(max_length=40)),
                ("status", models.CharField(default="open", max_length=20)),
                ("related", models.JSONField(default=dict)),
                ("suggested_actions", models.JSONField(default=list)),
                (
                    "candidate_version",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.pageversion"
                    ),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="check_items", to="opspilot.wikiknowledgebase"),
                ),
            ],
            options={
                "db_table": "opspilot_wiki_check_item",
            },
        ),
        migrations.AddField(
            model_name="buildrecord",
            name="knowledge_base",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="build_records", to="opspilot.wikiknowledgebase"),
        ),
    ]
