# Generated by Django 4.2.27 on 2026-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0060_buildrecord_knowledgepage_material_materialversion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmskill",
            name="wiki_knowledge_bases",
            field=models.ManyToManyField(blank=True, related_name="skills", to="opspilot.wikiknowledgebase", verbose_name="Wiki知识库"),
        ),
    ]
