# Generated by Django 4.2.27 on 2026-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0061_llmskill_wiki_knowledge_bases"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageversion",
            name="embedding",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
