# Generated by Django 4.2.27 on 2026-06-22 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0062_pageversion_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("idx", models.IntegerField(default=0)),
                ("text", models.TextField(default="")),
                ("heading_path", models.CharField(blank=True, default="", max_length=512)),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="opspilot.knowledgepage")),
                (
                    "version",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="opspilot.pageversion"
                    ),
                ),
            ],
            options={
                "db_table": "opspilot_wiki_page_chunk",
                "ordering": ["page_id", "idx"],
            },
        ),
    ]
