# Generated by Django 4.2.27 on 2026-06-24 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("opspilot", "0056_llmskill_skill_packages_skillpackage"),
        ("opspilot", "0063_pagechunk"),
    ]

    operations = []
