# Generated by Django 4.2.22 on 2025-11-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrainstance',
            name='user',
            field=models.CharField(blank=True, help_text='容器运行用户,格式: uid:gid 或 username，为空则使用镜像默认值', max_length=50, null=True, verbose_name='运行用户'),
        ),
        migrations.AddField(
            model_name='labimage',
            name='default_user',
            field=models.CharField(blank=True, help_text='容器运行用户,格式: uid:gid 或 username', max_length=50, null=True, verbose_name='运行用户'),
        ),
    ]
