# Generated by Django 4.2.15 on 2025-11-20 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0015_collector_package_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudRegionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('status', models.CharField(max_length=50, verbose_name='服务状态')),
                ('description', models.TextField(blank=True, verbose_name='服务描述')),
                ('cloud_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_mgmt.cloudregion', verbose_name='云区域')),
            ],
            options={
                'verbose_name': '云区域服务',
                'verbose_name_plural': '云区域服务',
                'unique_together': {('cloud_region', 'name')},
            },
        ),
    ]
