# Generated by Django 4.2.15 on 2025-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0016_cloudregionservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudregionservice',
            name='is_deployed',
            field=models.BooleanField(default=False, verbose_name='是否部署'),
        ),
    ]
