# Generated by Django 4.2.15 on 2025-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0017_cloudregionservice_is_deployed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudregionservice',
            name='is_deployed',
        ),
        migrations.AddField(
            model_name='cloudregionservice',
            name='deployed_message',
            field=models.TextField(blank=True, verbose_name='部署信息'),
        ),
        migrations.AddField(
            model_name='cloudregionservice',
            name='deployed_status',
            field=models.SmallIntegerField(default=0, verbose_name='部署状态'),
        ),
    ]
