# Generated by Django 4.2.15 on 2025-11-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0018_remove_cloudregionservice_is_deployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(default='host', max_length=50, verbose_name='节点类型'),
        ),
    ]
