# Generated by Django 4.2.15 on 2025-12-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0019_node_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='is_pre',
            field=models.BooleanField(default=True, verbose_name='是否预定义'),
        ),
    ]
