# Generated by Django 4.2.15 on 2025-12-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0020_collector_is_pre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudregionservice',
            name='message',
            field=models.TextField(blank=True, verbose_name='服务信息'),
        ),
    ]
