# Generated by Django 4.2.15 on 2025-12-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0021_cloudregionservice_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidecarenv',
            name='value',
            field=models.TextField(default='', verbose_name='变量内容'),
        ),
    ]
