# Generated by Django 4.2.15 on 2025-12-17 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0022_alter_sidecarenv_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='version_command',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='获取版本命令'),
        ),
        migrations.CreateModel(
            name='NodeComponentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('created_by', models.CharField(default='', max_length=32, verbose_name='Creator')),
                ('updated_by', models.CharField(default='', max_length=32, verbose_name='Updater')),
                ('domain', models.CharField(default='domain.com', max_length=100, verbose_name='Domain')),
                ('updated_by_domain', models.CharField(default='domain.com', max_length=100, verbose_name='updated by domain')),
                ('component_type', models.CharField(max_length=50, verbose_name='组件类型(控制器和采集器)')),
                ('component_id', models.CharField(max_length=100, verbose_name='组件ID')),
                ('version', models.CharField(max_length=100, verbose_name='版本号')),
                ('message', models.TextField(blank=True, default='', verbose_name='执行信息')),
                ('last_check_at', models.DateTimeField(auto_now=True, verbose_name='最后检查时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_versions', to='node_mgmt.node', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点组件版本信息',
                'verbose_name_plural': '节点组件版本信息',
                'unique_together': {('node', 'component_type', 'component_id')},
            },
        ),
    ]
