# Generated by Django 4.2.15 on 2025-12-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0023_controller_version_command_nodecomponentversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collector',
            name='enabled_default_config',
        ),
    ]
