# Generated by Django 4.2.15 on 2025-12-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0024_remove_collector_enabled_default_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodecomponentversion',
            name='latest_version',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='最新版本号'),
        ),
        migrations.AddField(
            model_name='nodecomponentversion',
            name='upgradeable',
            field=models.BooleanField(default=False, verbose_name='是否可升级'),
        ),
    ]
