# Generated by Django 4.2.16 on 2026-01-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0025_nodecomponentversion_latest_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllertasknode',
            name='passphrase',
            field=models.TextField(blank=True, default='', verbose_name='私钥密码短语'),
        ),
        migrations.AddField(
            model_name='controllertasknode',
            name='private_key',
            field=models.TextField(blank=True, default='', verbose_name='SSH私钥'),
        ),
    ]
