# Generated by Django 4.2.15 on 2026-01-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0026_controllertasknode_passphrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudregion',
            name='proxy_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='代理地址'),
        ),
    ]
