# Generated by Django 4.2.27 on 2026-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_mgmt', '0027_cloudregion_proxy_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='childconfig',
            name='config_section',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='配置段'),
        ),
    ]
