# Generated by Django 4.2.22 on 2026-03-16 03:43

import django.db.models.deletion
import django_minio_backend.models
from django.db import migrations, models

import apps.job_mgmt.models.playbook
import apps.job_mgmt.models.target


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DangerousPath",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("pattern", models.CharField(max_length=512, verbose_name="路径匹配规则")),
                (
                    "match_type",
                    models.CharField(choices=[("exact", "精确匹配"), ("regex", "正则匹配")], default="exact", max_length=32, verbose_name="匹配方式"),
                ),
                (
                    "level",
                    models.CharField(choices=[("confirm", "二次确认"), ("forbidden", "禁止分发")], default="forbidden", max_length=32, verbose_name="处理策略"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
            ],
            options={
                "verbose_name": "高危路径",
                "verbose_name_plural": "高危路径",
                "db_table": "job_dangerous_path",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DangerousRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("pattern", models.CharField(max_length=512, verbose_name="命令匹配规则")),
                (
                    "level",
                    models.CharField(choices=[("confirm", "二次确认"), ("forbidden", "禁止分发")], default="confirm", max_length=32, verbose_name="处理策略"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
            ],
            options={
                "verbose_name": "高危命令",
                "verbose_name_plural": "高危命令",
                "db_table": "job_dangerous_rule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DistributionFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_name", models.CharField(max_length=255, verbose_name="原始文件名")),
                ("file_key", models.CharField(max_length=512, verbose_name="存储路径")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="上传时间")),
            ],
            options={
                "verbose_name": "分发文件",
                "verbose_name_plural": "分发文件",
                "db_table": "job_distribution_file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Playbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, verbose_name="Playbook名称")),
                ("version", models.CharField(default="v1.0.0", max_length=32, verbose_name="版本号")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                ("readme", models.TextField(blank=True, default="", verbose_name="README内容")),
                ("file_list", models.JSONField(default=list, verbose_name="文件列表")),
                ("params", models.JSONField(default=list, verbose_name="参数定义")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django_minio_backend.models.MinioBackend(bucket_name="job-mgmt-private"),
                        upload_to=apps.job_mgmt.models.playbook.playbook_upload_path,
                        verbose_name="Playbook文件",
                    ),
                ),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
            ],
            options={
                "verbose_name": "Playbook",
                "verbose_name_plural": "Playbook",
                "db_table": "job_playbook",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, verbose_name="脚本名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                (
                    "script_type",
                    models.CharField(
                        choices=[("shell", "Shell"), ("python", "Python"), ("powershell", "PowerShell"), ("bat", "Batch")],
                        default="shell",
                        max_length=32,
                        verbose_name="脚本类型",
                    ),
                ),
                ("content", models.TextField(verbose_name="脚本内容")),
                ("params", models.JSONField(default=list, verbose_name="参数定义")),
                ("timeout", models.IntegerField(default=60, verbose_name="超时时间")),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
                ("is_built_in", models.BooleanField(default=False, verbose_name="是否内置")),
            ],
            options={
                "verbose_name": "脚本",
                "verbose_name_plural": "脚本",
                "db_table": "job_script",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, verbose_name="名称")),
                ("ip", models.GenericIPAddressField(verbose_name="IP地址")),
                (
                    "os_type",
                    models.CharField(choices=[("linux", "Linux"), ("windows", "Windows")], default="linux", max_length=32, verbose_name="操作系统"),
                ),
                ("cloud_region_id", models.BigIntegerField(blank=True, null=True, verbose_name="云区域ID")),
                ("node_id", models.CharField(blank=True, default="", max_length=64, verbose_name="节点ID")),
                (
                    "driver",
                    models.CharField(choices=[("ansible", "Ansible"), ("sidecar", "Sidecar")], default="ansible", max_length=32, verbose_name="执行驱动"),
                ),
                (
                    "credential_source",
                    models.CharField(choices=[("manual", "手动录入"), ("credential", "凭据管理")], default="manual", max_length=32, verbose_name="凭据来源"),
                ),
                ("credential_id", models.CharField(blank=True, default="", max_length=64, verbose_name="凭据ID")),
                ("ssh_port", models.IntegerField(default=22, verbose_name="SSH端口")),
                ("ssh_user", models.CharField(blank=True, default="", max_length=64, verbose_name="SSH用户名")),
                (
                    "ssh_credential_type",
                    models.CharField(choices=[("password", "密码"), ("key", "密钥")], default="password", max_length=32, verbose_name="SSH凭据类型"),
                ),
                ("ssh_password", models.CharField(blank=True, default="", max_length=256, verbose_name="SSH密码")),
                (
                    "ssh_key_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django_minio_backend.models.MinioBackend(bucket_name="job-mgmt-private"),
                        upload_to=apps.job_mgmt.models.target.ssh_key_upload_path,
                        verbose_name="SSH密钥文件",
                    ),
                ),
                ("winrm_port", models.IntegerField(default=5986, verbose_name="WinRM端口")),
                (
                    "winrm_scheme",
                    models.CharField(choices=[("http", "HTTP"), ("https", "HTTPS")], default="https", max_length=16, verbose_name="WinRM协议"),
                ),
                ("winrm_user", models.CharField(blank=True, default="", max_length=64, verbose_name="WinRM用户名")),
                ("winrm_password", models.CharField(blank=True, default="", max_length=256, verbose_name="WinRM密码")),
                ("winrm_cert_validation", models.BooleanField(default=True, verbose_name="WinRM证书验证")),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
            ],
            options={
                "verbose_name": "执行目标",
                "verbose_name_plural": "执行目标",
                "db_table": "job_target",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=128, verbose_name="任务名称")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                (
                    "job_type",
                    models.CharField(
                        choices=[("script", "脚本执行"), ("file_distribution", "文件分发"), ("playbook", "Playbook")],
                        max_length=32,
                        verbose_name="作业类型",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(choices=[("once", "单次执行"), ("cron", "周期执行")], default="once", max_length=32, verbose_name="调度类型"),
                ),
                ("cron_expression", models.CharField(blank=True, default="", max_length=128, verbose_name="Cron表达式")),
                ("scheduled_time", models.DateTimeField(blank=True, null=True, verbose_name="计划执行时间")),
                (
                    "target_source",
                    models.CharField(
                        choices=[("sync", "同步"), ("manual", "手动"), ("node_mgmt", "节点管理")],
                        default="manual",
                        max_length=32,
                        verbose_name="目标来源",
                    ),
                ),
                ("target_list", models.JSONField(default=list, verbose_name="目标列表")),
                ("params", models.JSONField(default=dict, verbose_name="执行参数")),
                (
                    "script_type",
                    models.CharField(
                        blank=True,
                        choices=[("shell", "Shell"), ("python", "Python"), ("powershell", "PowerShell"), ("bat", "Batch")],
                        default="",
                        max_length=32,
                        verbose_name="脚本类型",
                    ),
                ),
                ("script_content", models.TextField(blank=True, default="", verbose_name="脚本内容")),
                ("files", models.JSONField(default=list, verbose_name="分发文件列表")),
                ("target_path", models.CharField(blank=True, default="", max_length=512, verbose_name="目标路径")),
                ("timeout", models.IntegerField(default=300, verbose_name="超时时间")),
                (
                    "concurrency_policy",
                    models.CharField(
                        choices=[
                            ("skip", "跳过（上次未完成则跳过本次）"),
                            ("run", "运行（无论上次是否完成）"),
                            ("queue", "排队（等待上次完成后执行）"),
                        ],
                        default="skip",
                        max_length=32,
                        verbose_name="并发策略",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("periodic_task_id", models.IntegerField(blank=True, null=True, verbose_name="周期任务ID")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="上次执行时间")),
                ("run_count", models.IntegerField(default=0, verbose_name="执行次数")),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
                (
                    "playbook",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="job_mgmt.playbook", verbose_name="关联Playbook"
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="job_mgmt.script", verbose_name="关联脚本"),
                ),
            ],
            options={
                "verbose_name": "定时任务",
                "verbose_name_plural": "定时任务",
                "db_table": "job_scheduled_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("name", models.CharField(max_length=256, verbose_name="作业名称")),
                (
                    "job_type",
                    models.CharField(
                        choices=[("script", "脚本执行"), ("file_distribution", "文件分发"), ("playbook", "Playbook")],
                        max_length=32,
                        verbose_name="作业类型",
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[("manual", "手动执行"), ("scheduled", "定时任务"), ("api", "API调用")],
                        default="manual",
                        max_length=32,
                        verbose_name="触发来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("timeout", "超时"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=32,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "target_source",
                    models.CharField(
                        choices=[("sync", "同步"), ("manual", "手动"), ("node_mgmt", "节点管理")],
                        default="manual",
                        max_length=32,
                        verbose_name="目标来源",
                    ),
                ),
                ("target_list", models.JSONField(default=list, verbose_name="目标列表")),
                ("execution_results", models.JSONField(default=list, verbose_name="执行结果")),
                ("params", models.TextField(blank=True, default="", verbose_name="执行参数")),
                (
                    "script_type",
                    models.CharField(
                        blank=True,
                        choices=[("shell", "Shell"), ("python", "Python"), ("powershell", "PowerShell"), ("bat", "Batch")],
                        default="",
                        max_length=32,
                        verbose_name="脚本类型",
                    ),
                ),
                ("script_content", models.TextField(blank=True, default="", verbose_name="脚本内容")),
                ("files", models.JSONField(default=list, verbose_name="分发文件列表")),
                ("target_path", models.CharField(blank=True, default="", max_length=512, verbose_name="目标路径")),
                (
                    "overwrite_strategy",
                    models.CharField(
                        choices=[("overwrite", "覆盖已存在文件"), ("skip", "跳过已存在文件")],
                        default="overwrite",
                        max_length=32,
                        verbose_name="覆盖策略",
                    ),
                ),
                ("timeout", models.IntegerField(default=600, verbose_name="超时时间")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("total_count", models.IntegerField(default=0, verbose_name="总目标数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功数")),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败数")),
                ("executor_user", models.CharField(blank=True, default="", max_length=128, verbose_name="执行用户")),
                ("team", models.JSONField(default=list, verbose_name="团队ID列表")),
                (
                    "playbook",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="job_mgmt.playbook", verbose_name="关联Playbook"
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="job_mgmt.script", verbose_name="关联脚本"),
                ),
            ],
            options={
                "verbose_name": "作业执行",
                "verbose_name_plural": "作业执行",
                "db_table": "job_execution",
                "ordering": ["-created_at"],
            },
        ),
    ]
