# Generated by Django 4.2.27 on 2026-05-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_mgmt", "0002_target_winrm_transport_and_ssh_key_passphrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobexecution",
            name="callback_url",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="回调地址"),
        ),
    ]
