# Generated by Django 4.2.27 on 2026-05-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_mgmt", "0005_jobexecution_celery_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributionfile",
            name="is_permanent",
            field=models.BooleanField(default=False, verbose_name="永久保存"),
        ),
    ]
