# Generated by Django 4.2.27 on 2026-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_mgmt", "0006_add_is_permanent_to_distributionfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributionfile",
            name="team",
            field=models.IntegerField(blank=True, null=True, verbose_name="团队ID"),
        ),
    ]
