# Generated by Django 4.2.27 on 2026-06-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_mgmt", "0010_add_status_index_to_jobexecution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("running", "执行中"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("timeout", "超时"),
                    ("cancelling", "取消中"),
                    ("cancelled", "已取消"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
                verbose_name="执行状态",
            ),
        ),
    ]
