# Generated by Django 4.2.27 on 2026-06-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_mgmt', '0011_alter_jobexecution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexecution',
            name='callback_subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='NATS回调主题（nats通道）'),
        ),
        migrations.AddField(
            model_name='jobexecution',
            name='callback_type',
            field=models.CharField(choices=[('web', 'HTTP回调'), ('nats', 'NATS回调'), ('both', 'HTTP+NATS')], default='web', max_length=16, verbose_name='回调通道'),
        ),
        migrations.AlterField(
            model_name='jobexecution',
            name='callback_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='回调地址（web通道）'),
        ),
    ]
