import type { SimpleDashboardConfig } from '../common/simple-dashboard-core';

export const KAFKA_DASHBOARD_CONFIG: SimpleDashboardConfig = {
  routeKey: 'kafka',
  pageTitle: 'Kafka 监控仪表盘',
  objectFallbackName: 'Kafka',
  instanceType: 'kafka',
  collectionStatusQuery: "count({instance_type='kafka', collect_type='exporter', __$labels__}) by (instance_id)",
  metaItems: ['Kafka-Exporter', 'exporter'],
  metrics: [
    {
      name: 'kafka_brokers_gauge',
      display_name: 'Broker 数',
      description: 'Kafka 集群当前可发现的 Broker 数量。',
      unit: 'counts',
      query: 'sum(kafka_brokers_gauge{__$labels__})',
      color: '#2f6bff',
    },
    {
      name: 'kafka_under_replicated_partitions',
      display_name: '不同步分区数',
      description: '副本未全部同步的分区数量；非零时需优先排查副本健康。',
      unit: 'counts',
      query: 'sum(kafka_topic_partition_under_replicated_partition_gauge{__$labels__})',
      color: '#ff8a1f',
    },
    {
      name: 'kafka_max_consumergroup_lag',
      display_name: '最大消费者 Lag',
      description: '所有消费者组、Topic 和分区中当前最大的消费滞后。',
      unit: 'counts',
      query: 'max(kafka_consumergroup_lag_gauge{__$labels__})',
      color: '#ff4d4f',
    },
    {
      name: 'kafka_topic_partition_count',
      display_name: 'Topic 分区数',
      description: '当前已采集 Topic 的分区总数。',
      unit: 'counts',
      query: 'sum(kafka_topic_partitions_gauge{__$labels__})',
      color: '#13c2c2',
    },
  ],
  summaryCards: [
    {
      title: 'Broker 数',
      metric: 'kafka_brokers_gauge',
      unit: 'counts',
      color: '#2f6bff',
      icon: 'node',
      guide: [{ label: 'Broker 数', detail: 'Broker 数突变可能表示节点离线、扩缩容或采集异常。' }],
    },
    {
      title: '不同步分区数',
      metric: 'kafka_under_replicated_partitions',
      unit: 'counts',
      color: '#ff8a1f',
      icon: 'health',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '副本同步', detail: '正常状态为 0；非零表示至少一个分区未达到 ISR 副本要求。' }],
    },
    {
      title: '最大消费者 Lag',
      metric: 'kafka_max_consumergroup_lag',
      unit: 'counts',
      color: '#ff4d4f',
      icon: 'backlog',
      compare: true,
      compareFavorableDirection: 'down',
      guide: [{ label: '消费者 Lag', detail: '取当前最严重的消费者组分区滞后；持续升高说明消费速度落后于生产。' }],
    },
    {
      title: 'Topic 分区数',
      metric: 'kafka_topic_partition_count',
      unit: 'counts',
      color: '#13c2c2',
      icon: 'database',
      guide: [{ label: '分区规模', detail: '分区总数反映当前被监控集群的 Topic 和并行度规模。' }],
    },
  ],
  charts: [
    {
      title: '消费者 Lag 趋势',
      subtitle: '最大消费者组分区 Lag',
      metric: 'kafka_max_consumergroup_lag',
      guide: [{ label: 'Lag 趋势', detail: '折线展示最大 Lag 的时间变化；悬浮任一点可查看精确数值和时间。' }],
      series: [{ metric: 'kafka_max_consumergroup_lag', label: '最大 Lag', color: '#ff4d4f', unit: 'counts' }],
    },
    {
      title: '分区副本健康趋势',
      subtitle: '不同步副本分区数',
      metric: 'kafka_under_replicated_partitions',
      guide: [{ label: '副本健康', detail: '折线应稳定在 0；非零点表示需要检查 Broker、网络或磁盘同步。' }],
      series: [{ metric: 'kafka_under_replicated_partitions', label: '不同步分区', color: '#ff8a1f', unit: 'counts' }],
    },
  ],
  details: [],
};
