# Generated by Django 4.2.22 on 2025-11-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_time", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="通知时间")),
                ("app_module", models.CharField(db_index=True, max_length=100, verbose_name="模块")),
                ("content", models.TextField(verbose_name="通知内容")),
                ("is_read", models.BooleanField(db_index=True, default=False, verbose_name="是否已读")),
            ],
            options={
                "verbose_name": "通知消息",
                "verbose_name_plural": "通知消息",
                "db_table": "console_mgmt_notification",
                "ordering": ["-notification_time"],
                "indexes": [
                    models.Index(fields=["is_read", "-notification_time"], name="console_mgm_is_read_2e9ab6_idx"),
                    models.Index(fields=["app_module", "-notification_time"], name="console_mgm_app_mod_5cfdbd_idx"),
                ],
            },
        ),
    ]
