# Generated by Django 4.2.22 on 2025-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("console_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAppSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(db_index=True, max_length=255, verbose_name="用户名")),
                ("domain", models.CharField(db_index=True, max_length=255, verbose_name="域名")),
                ("app_config_list", models.JSONField(default=list, verbose_name="应用配置列表")),
            ],
            options={
                "verbose_name": "用户应用配置集",
                "verbose_name_plural": "用户应用配置集",
                "db_table": "console_mgmt_user_app_set",
                "indexes": [models.Index(fields=["username", "domain"], name="console_mgm_usernam_13fcee_idx")],
                "unique_together": {("username", "domain")},
            },
        ),
    ]
