# Generated by Django 4.2.27 on 2026-05-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console_mgmt", "0002_userappset"),
    ]

    operations = [
        migrations.AddField(model_name="notification", name="source", field=models.CharField(default="unknown", max_length=100, verbose_name="来源"),),
    ]
