# Generated by Django 4.2.27 on 2026-05-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("console_mgmt", "0003_add_notification_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification", name="is_read", field=models.BooleanField(db_index=True, default=False, verbose_name="是否已读（已废弃，保留兼容）"),
        ),
        migrations.CreateModel(
            name="NotificationRead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_read", models.BooleanField(default=False, verbose_name="是否已读")),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="已读时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否已删除")),
                (
                    "notification",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="read_states", to="console_mgmt.notification"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_reads", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "通知已读状态",
                "verbose_name_plural": "通知已读状态",
                "db_table": "console_mgmt_notification_read",
                "indexes": [
                    models.Index(fields=["user", "is_read"], name="console_mgm_user_id_90e037_idx"),
                    models.Index(fields=["user", "is_deleted"], name="console_mgm_user_id_963ec7_idx"),
                ],
                "unique_together": {("notification", "user")},
            },
        ),
    ]
