import os

METIS_DB_URL = os.getenv("METIS_DB_URL")

METIS_ELASTICSEARCH_URL = os.getenv("METIS_ELASTICSEARCH_URL")
METIS_ELASTICSEARCH_PASSWORD = os.getenv("METIS_ELASTICSEARCH_PASSWORD")

METIS_NEO4J_URL = os.getenv("METIS_NEO4J_URL")
METIS_NEO4J_USERNAME = os.getenv("METIS_NEO4J_USERNAME")
METIS_NEO4J_PASSWORD = os.getenv("METIS_NEO4J_PASSWORD")