from apps.job_mgmt.constants.choices import (  # noqa
    ConcurrencyPolicy,
    CredentialSource,
    DangerousLevel,
    ExecutionStatus,
    ExecutorDriver,
    JobType,
    OSType,
    OverwriteStrategy,
    ScheduleType,
    ScriptType,
    SSHCredentialType,
    TargetSource,
    TriggerSource,
    WinRMScheme,
)
