# Generated by Django 4.2.7 on 2025-12-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0009_alter_collectmodels_task_type"),
    ]

    operations = [
        migrations.AddField(model_name="collectmodels", name="team", field=models.JSONField(default=list, help_text="关联组织"),),
    ]
