# Generated by Django 4.2.7 on 2026-01-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0010_collectmodels_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain",
                 models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("model_id",
                 models.CharField(db_index=True, help_text="关联的模型ID", max_length=100, verbose_name="模型ID")),
                ("group_name", models.CharField(help_text="分组唯一标识，与attrs.attr_group关联", max_length=200,
                                                verbose_name="分组名称")),
                ("order", models.IntegerField(default=0, help_text="值越小越靠前，用于控制分组显示顺序",
                                              verbose_name="排序序号")),
                ("is_collapsed", models.BooleanField(default=False, help_text="前端展示时是否默认折叠该分组",
                                                     verbose_name="是否默认折叠")),
                ("description",
                 models.TextField(blank=True, default="", help_text="分组的详细说明", verbose_name="分组描述")),
                ("attr_orders",
                 models.JSONField(default=list, blank=True, null=True, help_text="该分组下属性的排序列表",
                                  verbose_name="属性排序")),
            ],
            options={
                "verbose_name": "字段分组",
                "verbose_name_plural": "字段分组",
                "db_table": "cmdb_field_group",
                "ordering": ["model_id", "order"],
                "indexes": [models.Index(fields=["model_id", "order"], name="idx_model_order")],
                "unique_together": {("model_id", "group_name")},
            },
        ),
    ]
