# Generated by Django 4.2.7 on 2026-03-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0012_userpersonalconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicEnumLibrary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("created_by", models.CharField(default="", max_length=32, verbose_name="Creator")),
                ("updated_by", models.CharField(default="", max_length=32, verbose_name="Updater")),
                ("domain", models.CharField(default="domain.com", max_length=100, verbose_name="Domain")),
                ("updated_by_domain", models.CharField(default="domain.com", max_length=100, verbose_name="updated by domain")),
                ("library_id", models.CharField(db_index=True, help_text="全局唯一标识，用于字段绑定引用", max_length=64, unique=True, verbose_name="公共选项库ID")),
                ("name", models.CharField(db_index=True, help_text="显示名称，支持中英文", max_length=128, verbose_name="公共选项库名称")),
                ("team", models.JSONField(default=list, help_text="关联的组织ID列表，用于权限控制", verbose_name="关联组织")),
                ("options", models.JSONField(default=list, help_text='枚举选项集合，结构为 [{"id": str, "name": str}]', verbose_name="选项列表")),
            ],
            options={
                "verbose_name": "公共选项库",
                "verbose_name_plural": "公共选项库",
                "db_table": "cmdb_public_enum_library",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["library_id"], name="idx_public_enum_lib_id"),
                    models.Index(fields=["name"], name="idx_public_enum_lib_name"),
                ],
            },
        ),
    ]
