# Generated by Django 4.2.7 on 2026-05-12 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_alter_collectmodels_task_type_configfileversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMgmtSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('name', models.CharField(default='节点管理同步', max_length=128, verbose_name='任务名称')),
                ('is_builtin', models.BooleanField(default=True, verbose_name='是否为系统内置任务')),
                ('auto_sync_enabled', models.BooleanField(default=True, verbose_name='是否自动同步')),
                ('auto_collect_enabled', models.BooleanField(default=True, verbose_name='是否自动采集')),
                ('sync_interval_minutes', models.PositiveIntegerField(default=5, verbose_name='同步周期(分钟)')),
                ('collect_interval_minutes', models.PositiveIntegerField(default=30, verbose_name='采集周期(分钟)')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('last_collect_at', models.DateTimeField(blank=True, null=True, verbose_name='最近采集时间')),
            ],
            options={
                'verbose_name': '节点管理同步配置',
                'verbose_name_plural': '节点管理同步配置',
            },
        ),
        migrations.AddField(
            model_name='collectmodels',
            name='is_system',
            field=models.BooleanField(default=False, help_text='是否为系统内置任务'),
        ),
        migrations.AddField(
            model_name='collectmodels',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='是否在普通采集页面展示'),
        ),
        migrations.AddField(
            model_name='collectmodels',
            name='system_code',
            field=models.CharField(blank=True, help_text='系统任务编码', max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='NodeMgmtSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('run_type', models.CharField(choices=[('sync', '同步'), ('collect', '采集')], max_length=32, verbose_name='执行类型')),
                ('status', models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('partial_success', '部分成功')], default='running', max_length=32, verbose_name='执行状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('summary_json', models.JSONField(default=dict, help_text='执行摘要')),
                ('detail_json', models.JSONField(default=dict, help_text='执行明细')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='cmdb.nodemgmtsyncconfig', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '节点管理同步记录',
                'verbose_name_plural': '节点管理同步记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
