# Generated by Django 4.2.27 on 2026-05-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0020_changerecord_scenario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configfileversion",
            name="collect_task",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的采集任务（手动创建时为空）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="config_file_versions",
                to="cmdb.collectmodels",
            ),
        ),
    ]
