# Generated by Django 4.2.27 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0021_alter_configfileversion_collect_task"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="configfileversion",
            index=models.Index(
                fields=["instance_id", "file_path", "created_at"],
                name="cmdb_config_inst_path_created_idx",
            ),
        ),
    ]
