# Generated by Django 4.2.7 on 2026-06-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0022_configfileversion_subscription_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectTaskCredentialHit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("object_key", models.CharField(max_length=255)),
                ("credential_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(choices=[("untested", "未探测"), ("success", "成功"), ("known_failed", "已知失败")], default="untested", max_length=32),
                ),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                ("cooldown_level", models.PositiveSmallIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("object_snapshot", models.JSONField(default=dict)),
            ],
            options={"verbose_name": "采集任务凭据命中状态", "verbose_name_plural": "采集任务凭据命中状态",},
        ),
        migrations.RemoveIndex(model_name="configfileversion", name="cmdb_config_inst_path_created_idx",),
        migrations.AddField(
            model_name="collecttaskcredentialhit",
            name="task",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="credential_hits", to="cmdb.collectmodels"),
        ),
        migrations.AddIndex(
            model_name="collecttaskcredentialhit", index=models.Index(fields=["task", "object_key"], name="cmdb_collect_hit_task_obj_idx"),
        ),
        migrations.AddIndex(
            model_name="collecttaskcredentialhit", index=models.Index(fields=["task", "status", "next_retry_at"], name="cmdb_collect_hit_retry_idx"),
        ),
        migrations.AlterUniqueTogether(name="collecttaskcredentialhit", unique_together={("task", "object_key", "credential_id")},),
    ]
