# Generated by Django 4.2.27 on 2026-06-08 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0023_collecttaskcredentialhit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmdbFileObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_id", models.UUIDField(default=uuid.uuid4, editable=False, help_text="文件业务 ID（对外引用）", unique=True)),
                ("bucket", models.CharField(help_text="对象存储 bucket", max_length=128)),
                ("object_key", models.CharField(help_text="对象存储 key", max_length=512, unique=True)),
                ("file_name", models.CharField(help_text="原始文件名", max_length=256)),
                ("file_size", models.BigIntegerField(default=0, help_text="文件大小（字节）")),
                ("mime_type", models.CharField(blank=True, default="", help_text="MIME 类型", max_length=128)),
                ("model_id", models.CharField(help_text="所属模型 ID", max_length=64)),
                ("attr_id", models.CharField(help_text="所属字段 ID", max_length=128)),
                ("inst_id", models.BigIntegerField(blank=True, help_text="所属实例 ID（提交前为空）", null=True)),
                ("uploader", models.CharField(help_text="上传者用户名", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待提交"), ("committed", "已提交"), ("orphaned", "待回收")], default="pending", help_text="生命周期状态", max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="更新时间")),
            ],
            options={
                "verbose_name": "CMDB 文件对象",
                "verbose_name_plural": "CMDB 文件对象",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="cmdb_cmdbfi_status_1aec50_idx"),
                    models.Index(fields=["inst_id"], name="cmdb_cmdbfi_inst_id_8fa11f_idx"),
                    models.Index(fields=["model_id", "attr_id"], name="cmdb_cmdbfi_model_i_61c1a6_idx"),
                ],
            },
        ),
    ]
