# Generated by Django 4.2.27 on 2026-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0023_collecttaskcredentialhit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerecord",
            name="scenario",
            field=models.CharField(
                choices=[
                    ("device_lifecycle", "设备流转"),
                    ("relation_change", "关系变更"),
                    ("ordinary_attribute_change", "普通属性变更"),
                    ("collect_automation_change", "自动采集"),
                    ("model_management_change", "模型管理变更"),
                    ("custom_reporting_change", "自定义报表变更"),
                ],
                db_index=True,
                default="ordinary_attribute_change",
                max_length=40,
                verbose_name="变更场景",
            ),
        ),
    ]
