# Generated by Django 4.2.27 on 2026-06-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0024_cmdbfileobject'),
        ('cmdb', '0024_custom_reporting'),
    ]

    operations = [
    ]
