# Generated by Django 4.2.27 on 2026-06-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0025_merge_0024_cmdbfileobject_0024_custom_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectmodels',
            name='topology_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='拓扑链路快照与过程数据'),
        ),
    ]
