# Generated by Django 4.2.27 on 2026-06-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0027_merge_reconcile_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerecord",
            name="scenario",
            field=models.CharField(
                choices=[
                    ("device_lifecycle", "设备流转"),
                    ("relation_change", "关系变更"),
                    ("ordinary_attribute_change", "普通属性变更"),
                    ("collect_automation_change", "自动采集"),
                    ("model_management_change", "模型管理变更"),
                    ("custom_reporting_change", "自定义上报变更"),
                ],
                db_index=True,
                default="ordinary_attribute_change",
                max_length=40,
                verbose_name="变更场景",
            ),
        ),
        migrations.CreateModel(
            name="IPAMReconcileSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("model_id", models.CharField(help_text="参与对账的 CI 模型 id，如 host/network", max_length=128)),
                ("ip_attr_id", models.CharField(help_text="该模型上承载 IP 的属性 id，如 ip_addr", max_length=128)),
                ("enabled", models.BooleanField(default=True, help_text="是否启用")),
                ("remark", models.CharField(blank=True, default="", help_text="备注", max_length=256)),
            ],
            options={"verbose_name": "IPAM对账来源", "db_table": "cmdb_ipam_reconcile_source", "unique_together": {("model_id", "ip_attr_id")},},
        ),
    ]
