# Generated by Django 4.2.27 on 2026-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb", "0029_seed_ipam_reconcile_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectmodels",
            name="input_method",
            field=models.PositiveSmallIntegerField(choices=[(0, "自动"), (1, "手动"), (2, "选子网")], default=0, help_text="录入方式"),
        ),
    ]
