# Generated by Django 4.2.27 on 2026-07-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0042_collectmodels_system_code_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="PCDiscoveryAuthority",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Created Time")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated Time")),
                ("pc_inst_name", models.CharField(help_text="PC 实例名（WIN-*/MAC-*）", max_length=128, unique=True)),
                ("last_snapshot_id", models.CharField(blank=True, default="", help_text="最近应用的快照 ID", max_length=64)),
                ("last_snapshot_time", models.DateTimeField(blank=True, help_text="最近应用快照的采集时间", null=True)),
                (
                    "authoritative_task",
                    models.ForeignKey(
                        help_text="当前权威采集任务", on_delete=django.db.models.deletion.PROTECT, related_name="owned_pcs", to="cmdb.collectmodels"
                    ),
                ),
                (
                    "pending_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="待移交任务（管理员已授权接管）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_pc_handovers",
                        to="cmdb.collectmodels",
                    ),
                ),
            ],
            options={
                "verbose_name": "PC发现权威任务",
                "db_table": "cmdb_pc_discovery_authority",
            },
        ),
    ]
