# Generated by Django 4.2.27 on 2026-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cmdb", "0050_scanfamilyrun_progress_hosts"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanhit",
            name="collect_task_id",
            field=models.PositiveIntegerField(blank=True, default=None, help_text="已生成的采集任务ID", null=True),
        ),
    ]
