# Generated by Django 4.2.22 on 2025-11-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0017_operationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, help_text="错误发生时间", verbose_name="创建时间")),
                ("username", models.CharField(db_index=True, help_text="触发错误的用户", max_length=100, verbose_name="用户名")),
                ("app", models.CharField(db_index=True, help_text="发生错误的应用模块", max_length=100, verbose_name="应用")),
                ("module", models.CharField(db_index=True, help_text="具体的功能模块", max_length=200, verbose_name="模块")),
                ("error_message", models.TextField(help_text="详细的错误描述", verbose_name="错误信息")),
                ("domain", models.CharField(db_index=True, default="domain.com", max_length=100, verbose_name="域名")),
            ],
            options={
                "verbose_name": "错误日志",
                "verbose_name_plural": "错误日志",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at", "app"], name="system_mgmt_created_7988d6_idx"),
                    models.Index(fields=["username", "-created_at"], name="system_mgmt_usernam_9987c6_idx"),
                    models.Index(fields=["app", "module", "-created_at"], name="system_mgmt_app_e7ee19_idx"),
                ],
            },
        ),
    ]
