# Generated by Django 4.2.22 on 2025-11-20 02:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0019_init_password_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_locked_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="账号锁定截止时间"),
        ),
        migrations.AddField(
            model_name="user",
            name="password_error_count",
            field=models.IntegerField(default=0, verbose_name="密码错误次数"),
        ),
        migrations.AddField(
            model_name="user",
            name="password_last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="密码最后修改时间"),
        ),
    ]
