# Generated by Django 4.2.22 on 2026-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0025_add_group_parent_id_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("enterprise_wechat", "Enterprise Wechat"),
                    ("enterprise_wechat_bot", "Enterprise Wechat Bot"),
                    ("nats", "NATS"),
                    ("feishu_bot", "Feishu Bot"),
                    ("dingtalk_bot", "DingTalk Bot"),
                    ("custom_webhook", "Custom Webhook"),
                ],
                max_length=30,
            ),
        ),
    ]
