# Generated by Django 4.2.27 on 2026-05-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0031_sensitive_info_authorization_and_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorlog",
            name="stack_trace",
            field=models.TextField(default="", help_text="详细的堆栈错误", verbose_name="堆栈信息"),
        ),
    ]
