# Generated by Django 4.2.27 on 2026-06-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_mgmt", "0032_errorlog_stack_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="detail",
            field=models.JSONField(blank=True, default=dict, verbose_name="Detail"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=100, verbose_name="Target ID"),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="target_type",
            field=models.CharField(blank=True, db_index=True, default="", max_length=50, verbose_name="Target Type"),
        ),
    ]
