# Generated by Django 4.2.27 on 2026-07-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_mgmt', '0038_imnotificationchannel_imnotificationusermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=36, null=True),
        ),
    ]
