# Generated by Django 4.2.15 on 2025-11-19 05:57

import apps.core.fields.s3_json_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_alter_eventrawdata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('source_id', models.CharField(db_index=True, max_length=100, verbose_name='资源ID')),
                ('snapshots', apps.core.fields.s3_json_field.S3JSONField(bucket_name='log-alert-snapshots', compressed=True, default=list, help_text='累积存储告警下所有事件的原始数据', max_length=500, upload_to=apps.core.fields.s3_json_field.s3_json_upload_path, verbose_name='快照数据集合')),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='log.alert', verbose_name='关联告警')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.policy', verbose_name='关联策略')),
            ],
            options={
                'verbose_name': '告警快照',
                'verbose_name_plural': '告警快照',
                'indexes': [models.Index(fields=['policy', 'source_id'], name='log_alertsn_policy__aa555c_idx')],
            },
        ),
    ]
