# Generated by Django 4.2.15 on 2025-11-19 06:01

import apps.core.fields.s3_json_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_alertsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsnapshot',
            name='snapshots',
            field=apps.core.fields.s3_json_field.S3JSONField(bucket_name='log-alert-raw-data', compressed=True, default=list, help_text='累积存储告警下所有事件的原始数据', max_length=500, upload_to=apps.core.fields.s3_json_field.s3_json_upload_path, verbose_name='快照数据集合'),
        ),
    ]
