# Generated by Django 4.2.27 on 2026-03-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_alter_alertsnapshot_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecttype',
            name='config_section',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='配置段'),
        ),
    ]
