# Generated by Django 4.2.27 on 2026-03-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_add_config_section_to_collecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecttype',
            name='display_category',
            field=models.CharField(default='', max_length=50, verbose_name='展示分类'),
        ),
    ]
